### PR TITLE
Section 2

### PR DESCRIPTION
**Pull request by ShalomiAhavah**
CTA box styling & positioning & border
Article Border
CTA Responsiveness

### CODE REVIEW

**Comment by josh76543210** [comment]
The CTA box does look improved but your changes are causing issues with other parts of the code. Updating the css for the CTA box should not affect the articles.

Here are screenshots of what the site looks like now (first screenshot) and what it looks like with your changes(second screenshot). As you can see below, the articles are no longer contained correctly. I would suggest working in smaller steps and making sure you are only changing the css for the element you are currently working on.

Screenshot 2024-04-08 at 15-39-26 Frontend Mentor Huddle landing page with alternating feature blocks

Screenshot 2024-04-08 at 15-39-43 Frontend Mentor Huddle landing page with alternating feature blocks

**Review by josh76543210 — CHANGES_REQUESTED** [review]
Not able to merge due to the code breaking the article boxes.

**Comment by ShalomiAhavah** [comment]
Hey!
So sorry for the delay. 
I hope this is okay now? If not I will have to fix it sometime next week as I will be traveling for the next few days.
Thank you for your patience, Josh!
Have a nice day👍🏼

**Review by josh76543210 — CHANGES_REQUESTED** [review]
Still the same issue.

**Pull request closed without merging**
